version: 0.6.2.{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
image: Visual Studio 2015
environment:
  OLW_CONFIG: Release
  OlwBloggerClientId: 597389294595-271ukaucs8ghmc6c6cnhrbef2c02g5qa.apps.googleusercontent.com
  OlwBloggerClientSecret:
    secure: ym7cbPINJz58iEgVlQCDbRz2W1CTYnxWsvMpMvxHFY4=
  SignClientSecret:
    secure: CHm+63iqVR0ddIHjGwE8nYF2EdUikH5VzCcszekUwptHkCLTuJ3C9ci8fcyox03s
nuget:
  disable_publish_on_pr: true
build_script:
- cmd: ./build.cmd
test: off
install:
  - cmd: nuget install SignClient -Version 0.7.0 -SolutionDir %APPVEYOR_BUILD_FOLDER% -Verbosity quiet -ExcludeVersion
after_build:
  - ps: '.\SignClient\Sign-Package.ps1'  
artifacts:
- path: releases\*
  name: Setup
deploy:
- provider: AzureBlob
  storage_account_name: olw
  storage_access_key:
    secure: GruVAC0VrJlbCP3AYz5XownU5bxltZBuGinJ9KwdedM12B07msVLwLYWAsWfWA8Cq6xxt3QN2tKMsDnkzSxSenYFBHZEkGXwRdmh9K/a9jReoNUeQukP/RXRqsS0otFh
  container: nightly
  on:
    branch: master
